name: release-solution-to-prod-reusable
# Reusable workflow
# convert solution to managed (using a build PowerPlatform environment for the conversion)
# upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  workflow_call:
    inputs: 
      solution_name:
        description: 'The solution name.'
        type: string
        default: akshaytest       
      solution_shipping_folder:
        description: 'Folder name for staging the exported solution *do not change*'        
        type: string
        default: out/ship/
      solution_outbound_folder:
        description: 'Staging the unpacked solution folder before check-in *do not change*'
        type: string
        default: out/solutions/
      solution_source_folder: 
        description: 'Folder name to be created and checked in *do not change*'
        type: string
        default: solutions/
      solution_release_folder:
        description: 'Folder where the released binaries are going to be hosted *do not change*'
        type: string
        default: out/release
      BUILD_ENVIRONMENT_URL:
        description: 'Build environment URL.'
        type: string
        required: true      
      PRODUCTION_ENVIRONMENT_URL: 
        description: 'Production environment URL.'
        type: string
        required: true
      CLIENT_ID: 
        description: 'The client ID.'
        type: string
        required: true
      TENANT_ID: 
        description: 'The tenant ID.'
        type: string
        required: true
    secrets:
      POWERAPPS:
        description: 'The secret value for authentication using SPN'
        required: true

jobs:
  convert-to-managed:
    runs-on: ubuntu-latest  # Prefer Linux runner to avoid file locking issues

    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Install Power Platform CLI
      uses: akshaypawar2508/powerplatform-actions/actions-install@v0

    - name: Pack solution
      uses: akshaypawar2508/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: ${{ inputs.solution_source_folder }}/${{ inputs.solution_name }}
        solution-file: ${{ inputs.solution_outbound_folder }}/${{ inputs.solution_name }}.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: akshaypawar2508/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ inputs.BUILD_ENVIRONMENT_URL }}
        app-id: ${{ inputs.CLIENT_ID }}
        client-secret: ${{ secrets.POWERAPPS }}
        tenant-id: ${{ inputs.TENANT_ID }}
        solution-file: ${{ inputs.solution_outbound_folder }}/${{ inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: akshaypawar2508/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ inputs.BUILD_ENVIRONMENT_URL }}
        app-id: ${{ inputs.CLIENT_ID }}
        client-secret: ${{ secrets.POWERAPPS }} 
        tenant-id: ${{ inputs.TENANT_ID }}
        solution-name: ${{ inputs.solution_name }}
        managed: true
        solution-output-file: ${{ inputs.solution_shipping_folder }}/${{ inputs.solution_name }}_managed.zip
        
    - name: Branch solution - prepare for PR
      uses: akshaypawar2508/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ inputs.solution_source_folder }}/${{ inputs.solution_name }}
        solution-target-folder: ${{ inputs.solution_release_folder }}/${{ inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v4
      with:
        name: managedSolutions
        path: ${{ inputs.solution_shipping_folder }}/

  release-to-prod:
    needs: convert-to-managed
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Download the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v4
      with:
        name: managedSolutions
        path: ${{ inputs.solution_release_folder }}

    - name: Import solution to prod environment
      uses: akshaypawar2508/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ inputs.PRODUCTION_ENVIRONMENT_URL }}
        app-id: ${{ inputs.CLIENT_ID }}
        client-secret: ${{ secrets.POWERAPPS }}
        tenant-id: ${{ inputs.TENANT_ID }}
        solution-file: ${{ inputs.solution_release_folder }}/${{ inputs.solution_name }}_managed.zip
        force-overwrite: true
        publish-changes: true
